### ISSUE TITLE
Spin up a landing page, rubyatscale.org

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/packs-specification#10]
- focus on content
- look at a couple of landing pages, try to generalize what the structure is
- 

# Content
- Above the fold messaging 

# Examples/Inspiration
https://sorbet.org
dry-rb.org
https://rubyonrails.org
hanami

**Comment by professor** [comment]
We are asking for  [rubyscale.org](http://rubyscale.org/) to redircet to https://github.com/rubyatscale
